/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablas;
import javax.swing.AbstractAction;
import javax.swing.InputMap;
import javax.swing.ActionMap;
import javax.swing.KeyStroke;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import javax.swing.JComponent;
import javax.swing.ScrollPaneConstants;

/**
 *
 * @author Joshua
 */
public class FORMTABLAS extends javax.swing.JFrame {
  TableModel a=new TableModel();
  int NumeroColumnas=5;
  
    /**
     * Creates new form FORMTABLAS
     */
    public FORMTABLAS() {
        
        initComponents();
        
         addKeyBindingsToTable();
         

    }
    
    private void addKeyBindingsToTable() {
       
    // Get the model from the table
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    // Bind Enter and Down keys
    InputMap im = jTable1.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    ActionMap am = jTable1.getActionMap();

    im.put(KeyStroke.getKeyStroke("ENTER"), "checkAndAddRow");
    im.put(KeyStroke.getKeyStroke("DOWN"), "checkAndAddRow");
    im.put(KeyStroke.getKeyStroke("RIGHT"), "columna");
    am.put("columna", new AbstractAction() {
    @Override
    public void actionPerformed(ActionEvent e) {
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        int colCount = model.getColumnCount();

        // Add new column if you're at the last column
        if (col == colCount - 1) {
            NumeroColumnas++;
            model.addColumn("Tabla " + NumeroColumnas);

            // Fill existing rows in new column with nulls (optional but safe)
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(null, i, model.getColumnCount() - 1);
            }
        }

        // Move to the next column (the newly created one, or the next existing one)
        int nextCol = Math.min(col + 1, model.getColumnCount() - 1);
        jTable1.changeSelection(row, nextCol, false, false);
    }
});
    am.put("checkAndAddRow", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();
            int rowCount = model.getRowCount();

            // If we're on the last row, add a new empty row
            if (row == rowCount - 1) {
                int colCount = model.getColumnCount();
                Object[] emptyRow = new Object[colCount];
                model.addRow(emptyRow);
            }

            // Move selection to the next row
            int nextRow = Math.min(row + 1, model.getRowCount() - 1);
            jTable1.changeSelection(nextRow, col, false, false);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable1.setModel(a.crearTabla());
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMTABLAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
