/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gm.com.gt.proyecto4;
import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.KeyStroke;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import java.util.LinkedList;

import java.awt.event.ActionEvent;

/**
 *PARTE VISUAL DEL PROYECTO
 * @author Joshua
 */
public class FORMTABLAS extends javax.swing.JFrame implements java.io.Serializable  {
  TableModel a=new TableModel();
  int NumeroColumnas=5;
  private LinkedList<JTabbedPane> lista = new LinkedList<>();

    /**
     * Creates new form FORMTABLAS
     */
    public FORMTABLAS() {
        
        initComponents();
        
         addKeyBindingsToTable();
         

    }
    
/***
 * esto crea un nuevo jtable y jscrollpane
 */
    private void NuevaHoja() {
    
    TableModel nuevoModelo = new TableModel();
    JTable nuevaTabla = new JTable(nuevoModelo.crearTabla());
    nuevaTabla.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
    JScrollPane scrollPane = new JScrollPane(nuevaTabla);
    scrollPane.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);

    // Crear nuevo JTabbedPane y agregar la tabla
    JTabbedPane subTab = new JTabbedPane();
    subTab.addTab("Hoja", scrollPane);

    // Agregar el nuevo subTab al principal
    int index = lista.size() + 2;
    jTabbedPane2.addTab("Tabla " + index, subTab);

    // Guardar en la lista enlazada
    lista.add(subTab);
}
/***
 * funcion para a;adirle listeners a la tabla
 */
    private void addKeyBindingsToTable() {
       
    // obtener modelo del jtable
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

    
    InputMap im = jTable1.getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
    ActionMap am = jTable1.getActionMap();
    

    im.put(KeyStroke.getKeyStroke("ENTER"), "checkAndAddRow");
    im.put(KeyStroke.getKeyStroke("DOWN"), "checkAndAddRow");
    im.put(KeyStroke.getKeyStroke("RIGHT"), "columna");
    am.put("columna", new AbstractAction() {
    @Override
    /***
     * funcion para crear nuevas columnas y filas
     */
    public void actionPerformed(ActionEvent e) {
        int row = jTable1.getSelectedRow();
        int col = jTable1.getSelectedColumn();
        int colCount = model.getColumnCount();

        
        if (col == colCount - 1 && colCount<26) {
            ConvertirLetra letra=new ConvertirLetra();
            NumeroColumnas++;
            model.addColumn(letra.letras(NumeroColumnas));

            // llenar con nulo las columnas generadsa
            for (int i = 0; i < model.getRowCount(); i++) {
                model.setValueAt(null, i, model.getColumnCount() - 1);
            }
        }

        // mover a la siguiente columna
        int nextCol = Math.min(col + 1, model.getColumnCount() - 1);
        jTable1.changeSelection(row, nextCol, false, false);
    }
});
    am.put("checkAndAddRow", new AbstractAction() {
        @Override
        public void actionPerformed(ActionEvent e) {
            int row = jTable1.getSelectedRow();
            int col = jTable1.getSelectedColumn();
            int rowCount = model.getRowCount();

            
            if (row == rowCount - 1) {
                int colCount = model.getColumnCount();
                Object[] emptyRow = new Object[colCount];
                model.addRow(emptyRow);
            }

           
            int nextRow = Math.min(row + 1, model.getRowCount() - 1);
            jTable1.changeSelection(nextRow, col, false, false);
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED);
        jTable1.setModel(a.crearTabla());
        jScrollPane1.setViewportView(jTable1);

        jTabbedPane2.addTab("Tabla 1", jScrollPane1);

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem1.setText("Nueva Hoja");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        NuevaHoja();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORMTABLAS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
